extends Node

var Standard = [
  {"german": "hallo", "english": "hello"},
  {"german": "tschüss", "english": "bye"},
  {"german": "bitte", "english": "please / you're welcome"},
  {"german": "danke", "english": "thank you"},
  {"german": "ja", "english": "yes"},
  {"german": "nein", "english": "no"},
  {"german": "vielleicht", "english": "maybe"},
  {"german": "natürlich", "english": "of course"},
  {"german": "entschuldigung", "english": "excuse me / sorry"},
  {"german": "willkommen", "english": "welcome"},

  {"german": "der Mann", "english": "man"},
  {"german": "die Frau", "english": "woman"},
  {"german": "das Kind", "english": "child"},
  {"german": "der Freund", "english": "friend (male)"},
  {"german": "die Freundin", "english": "friend (female)"},
  {"german": "die Familie", "english": "family"},
  {"german": "der Name", "english": "name"},
  {"german": "die Person", "english": "person"},
  {"german": "der Lehrer", "english": "teacher (male)"},
  {"german": "die Lehrerin", "english": "teacher (female)"},

  {"german": "das Haus", "english": "house"},
  {"german": "die Wohnung", "english": "apartment"},
  {"german": "das Zimmer", "english": "room"},
  {"german": "die Tür", "english": "door"},
  {"german": "das Fenster", "english": "window"},
  {"german": "der Tisch", "english": "table"},
  {"german": "der Stuhl", "english": "chair"},
  {"german": "das Bett", "english": "bed"},
  {"german": "das Handy", "english": "mobile phone"},
  {"german": "der Computer", "english": "computer"},

  {"german": "das Wasser", "english": "water"},
  {"german": "der Kaffee", "english": "coffee"},
  {"german": "der Tee", "english": "tea"},
  {"german": "das Brot", "english": "bread"},
  {"german": "das Fleisch", "english": "meat"},
  {"german": "das Gemüse", "english": "vegetables"},
  {"german": "das Obst", "english": "fruit"},
  {"german": "die Milch", "english": "milk"},
  {"german": "das Frühstück", "english": "breakfast"},
  {"german": "das Abendessen", "english": "dinner"},

  {"german": "der Tag", "english": "day"},
  {"german": "die Nacht", "english": "night"},
  {"german": "der Morgen", "english": "morning"},
  {"german": "der Abend", "english": "evening"},
  {"german": "die Woche", "english": "week"},
  {"german": "der Monat", "english": "month"},
  {"german": "das Jahr", "english": "year"},
  {"german": "heute", "english": "today"},
  {"german": "morgen", "english": "tomorrow"},
  {"german": "jetzt", "english": "now"},

  {"german": "sein", "english": "to be"},
  {"german": "haben", "english": "to have"},
  {"german": "gehen", "english": "to go"},
  {"german": "kommen", "english": "to come"},
  {"german": "machen", "english": "to do / make"},
  {"german": "sagen", "english": "to say"},
  {"german": "sehen", "english": "to see"},
  {"german": "geben", "english": "to give"},
  {"german": "wissen", "english": "to know (fact)"},
  {"german": "kennen", "english": "to know (person/place)"},

  {"german": "wollen", "english": "to want"},
  {"german": "brauchen", "english": "to need"},
  {"german": "finden", "english": "to find"},
  {"german": "arbeiten", "english": "to work"},
  {"german": "lernen", "english": "to learn"},
  {"german": "spielen", "english": "to play"},
  {"german": "sprechen", "english": "to speak"},
  {"german": "hören", "english": "to hear"},
  {"german": "essen", "english": "to eat"},
  {"german": "trinken", "english": "to drink"},

  {"german": "gut", "english": "good"},
  {"german": "schlecht", "english": "bad"},
  {"german": "groß", "english": "big"},
  {"german": "klein", "english": "small"},
  {"german": "alt", "english": "old"},
  {"german": "jung", "english": "young"},
  {"german": "neu", "english": "new"},
  {"german": "schnell", "english": "fast"},
  {"german": "langsam", "english": "slow"},
  {"german": "wichtig", "english": "important"},

  {"german": "hier", "english": "here"},
  {"german": "dort", "english": "there"},
  {"german": "wo", "english": "where"},
  {"german": "wann", "english": "when"},
  {"german": "warum", "english": "why"},
  {"german": "wie", "english": "how"},
  {"german": "was", "english": "what"},
  {"german": "wer", "english": "who"},
  {"german": "viel", "english": "much / many"},
  {"german": "mehr", "english": "more"},

  {"german": "eins", "english": "one"},
  {"german": "zwei", "english": "two"},
  {"german": "drei", "english": "three"},
  {"german": "vier", "english": "four"},
  {"german": "fünf", "english": "five"},
  {"german": "sechs", "english": "six"},
  {"german": "sieben", "english": "seven"},
  {"german": "acht", "english": "eight"},
  {"german": "neun", "english": "nine"},
  {"german": "zehn", "english": "ten"}
]
var Animals = [
  {"german": "der Hund", "english": "dog"},
  {"german": "die Katze", "english": "cat"},
  {"german": "der Vogel", "english": "bird"},
  {"german": "der Fisch", "english": "fish"},
  {"german": "das Pferd", "english": "horse"},
  {"german": "die Kuh", "english": "cow"},
  {"german": "das Schwein", "english": "pig"},
  {"german": "das Schaf", "english": "sheep"},
  {"german": "die Ziege", "english": "goat"},
  {"german": "das Huhn", "english": "chicken"},

  {"german": "der Hahn", "english": "rooster"},
  {"german": "die Ente", "english": "duck"},
  {"german": "die Gans", "english": "goose"},
  {"german": "der Truthahn", "english": "turkey"},
  {"german": "der Esel", "english": "donkey"},
  {"german": "das Kaninchen", "english": "rabbit"},
  {"german": "die Maus", "english": "mouse"},
  {"german": "die Ratte", "english": "rat"},
  {"german": "das Meerschweinchen", "english": "guinea pig"},
  {"german": "der Hamster", "english": "hamster"},

  {"german": "der Löwe", "english": "lion"},
  {"german": "der Tiger", "english": "tiger"},
  {"german": "der Elefant", "english": "elephant"},
  {"german": "die Giraffe", "english": "giraffe"},
  {"german": "der Affe", "english": "monkey"},
  {"german": "der Bär", "english": "bear"},
  {"german": "der Wolf", "english": "wolf"},
  {"german": "der Fuchs", "english": "fox"},
  {"german": "das Zebra", "english": "zebra"},
  {"german": "das Nilpferd", "english": "hippopotamus"},

  {"german": "das Nashorn", "english": "rhinoceros"},
  {"german": "der Leopard", "english": "leopard"},
  {"german": "der Gepard", "english": "cheetah"},
  {"german": "das Krokodil", "english": "crocodile"},
  {"german": "der Alligator", "english": "alligator"},
  {"german": "die Schlange", "english": "snake"},
  {"german": "die Schildkröte", "english": "turtle"},
  {"german": "der Frosch", "english": "frog"},
  {"german": "die Eule", "english": "owl"},
  {"german": "der Adler", "english": "eagle"},

  {"german": "der Papagei", "english": "parrot"},
  {"german": "der Pinguin", "english": "penguin"},
  {"german": "der Delfin", "english": "dolphin"},
  {"german": "der Wal", "english": "whale"},
  {"german": "der Hai", "english": "shark"},
  {"german": "die Krabbe", "english": "crab"},
  {"german": "der Oktopus", "english": "octopus"},
  {"german": "die Qualle", "english": "jellyfish"},
  {"german": "die Biene", "english": "bee"},
  {"german": "der Schmetterling", "english": "butterfly"},

  {"german": "die Ameise", "english": "ant"},
  {"german": "die Spinne", "english": "spider"},
  {"german": "die Fliege", "english": "fly"},
  {"german": "die Mücke", "english": "mosquito"},
  {"german": "der Käfer", "english": "beetle"},
  {"german": "der Marienkäfer", "english": "ladybug"},
  {"german": "der Igel", "english": "hedgehog"},
  {"german": "der Maulwurf", "english": "mole"},
  {"german": "der Hirsch", "english": "deer"},
  {"german": "das Reh", "english": "roe deer"},

  {"german": "das Wildschwein", "english": "wild boar"},
  {"german": "der Hase", "english": "hare"},
  {"german": "das Lama", "english": "llama"},
  {"german": "das Alpaka", "english": "alpaca"},
  {"german": "das Kamel", "english": "camel"},
  {"german": "der Panda", "english": "panda"},
  {"german": "der Koala", "english": "koala"},
  {"german": "das Känguru", "english": "kangaroo"},
  {"german": "der Waschbär", "english": "raccoon"},
  {"german": "das Eichhörnchen", "english": "squirrel"},

  {"german": "der Seehund", "english": "seal"},
  {"german": "der Seelöwe", "english": "sea lion"},
  {"german": "der Pelikan", "english": "pelican"},
  {"german": "der Flamingo", "english": "flamingo"},
  {"german": "der Strauß", "english": "ostrich"},
  {"german": "der Pfau", "english": "peacock"},
  {"german": "der Rabe", "english": "raven"},
  {"german": "die Taube", "english": "pigeon"},
  {"german": "der Specht", "english": "woodpecker"},
  {"german": "der Fink", "english": "finch"},

  {"german": "die Forelle", "english": "trout"},
  {"german": "der Lachs", "english": "salmon"},
  {"german": "der Thunfisch", "english": "tuna"},
  {"german": "der Hering", "english": "herring"},
  {"german": "die Garnele", "english": "shrimp"},
  {"german": "die Auster", "english": "oyster"},
  {"german": "die Muschel", "english": "mussel"},
  {"german": "der Storch", "english": "stork"},
  {"german": "der Uhu", "english": "eagle owl"},
  {"german": "die Fledermaus", "english": "bat"},
  {"german": "Der Hund ist sehr freundlich.", "english": "The dog is very friendly."},
  {"german": "Die Katze schläft auf dem Sofa.", "english": "The cat is sleeping on the sofa."},
  {"german": "Wir haben einen kleinen Hamster.", "english": "We have a small hamster."},
  {"german": "Der Vogel singt am Morgen.", "english": "The bird sings in the morning."},
  {"german": "Ich sehe einen Elefanten im Zoo.", "english": "I see an elephant at the zoo."},
  {"german": "Der Löwe ist ein wildes Tier.", "english": "The lion is a wild animal."},
  {"german": "Die Kuh gibt Milch.", "english": "The cow gives milk."},
  {"german": "Das Pferd läuft sehr schnell.", "english": "The horse runs very fast."},
  {"german": "Die Maus ist sehr klein.", "english": "The mouse is very small."},
  {"german": "Der Bär lebt im Wald.", "english": "The bear lives in the forest."},
  {"german": "Die Fische schwimmen im Wasser.", "english": "The fish are swimming in the water."},
  {"german": "Wir füttern die Tiere im Garten.", "english": "We feed the animals in the garden."},
  {"german": "Der Affe klettert auf einen Baum.", "english": "The monkey climbs a tree."},
  {"german": "Die Schlange ist lang und dünn.", "english": "The snake is long and thin."},
  {"german": "Ich mag Tiere sehr.", "english": "I like animals very much."}
]
var Food = [
  {"german": "das Brot", "english": "bread"},
  {"german": "das Brötchen", "english": "bread roll"},
  {"german": "der Reis", "english": "rice"},
  {"german": "die Nudeln", "english": "pasta"},
  {"german": "die Kartoffel", "english": "potato"},
  {"german": "die Pommes", "english": "fries"},
  {"german": "die Pizza", "english": "pizza"},
  {"german": "der Hamburger", "english": "hamburger"},
  {"german": "das Sandwich", "english": "sandwich"},
  {"german": "die Suppe", "english": "soup"},

  {"german": "der Salat", "english": "salad"},
  {"german": "das Fleisch", "english": "meat"},
  {"german": "das Hähnchen", "english": "chicken (meat)"},
  {"german": "das Rindfleisch", "english": "beef"},
  {"german": "das Schweinefleisch", "english": "pork"},
  {"german": "der Fisch", "english": "fish"},
  {"german": "das Ei", "english": "egg"},
  {"german": "der Käse", "english": "cheese"},
  {"german": "die Wurst", "english": "sausage"},
  {"german": "der Schinken", "english": "ham"},

  {"german": "die Milch", "english": "milk"},
  {"german": "der Joghurt", "english": "yogurt"},
  {"german": "die Butter", "english": "butter"},
  {"german": "die Sahne", "english": "cream"},
  {"german": "der Quark", "english": "curd cheese"},
  {"german": "das Müsli", "english": "muesli"},
  {"german": "die Marmelade", "english": "jam"},
  {"german": "der Honig", "english": "honey"},
  {"german": "der Zucker", "english": "sugar"},
  {"german": "das Salz", "english": "salt"},

  {"german": "der Pfeffer", "english": "pepper"},
  {"german": "das Öl", "english": "oil"},
  {"german": "der Essig", "english": "vinegar"},
  {"german": "die Soße", "english": "sauce"},
  {"german": "der Senf", "english": "mustard"},
  {"german": "der Ketchup", "english": "ketchup"},
  {"german": "die Mayonnaise", "english": "mayonnaise"},
  {"german": "die Zwiebel", "english": "onion"},
  {"german": "der Knoblauch", "english": "garlic"},
  {"german": "die Karotte", "english": "carrot"},

  {"german": "die Tomate", "english": "tomato"},
  {"german": "die Gurke", "english": "cucumber"},
  {"german": "die Paprika", "english": "bell pepper"},
  {"german": "der Salatkopf", "english": "lettuce"},
  {"german": "der Brokkoli", "english": "broccoli"},
  {"german": "der Spinat", "english": "spinach"},
  {"german": "der Mais", "english": "corn"},
  {"german": "die Bohne", "english": "bean"},
  {"german": "die Erbse", "english": "pea"},
  {"german": "der Pilz", "english": "mushroom"},

  {"german": "der Apfel", "english": "apple"},
  {"german": "die Banane", "english": "banana"},
  {"german": "die Orange", "english": "orange"},
  {"german": "die Zitrone", "english": "lemon"},
  {"german": "die Erdbeere", "english": "strawberry"},
  {"german": "die Kirsche", "english": "cherry"},
  {"german": "die Traube", "english": "grape"},
  {"german": "die Birne", "english": "pear"},
  {"german": "die Ananas", "english": "pineapple"},
  {"german": "die Mango", "english": "mango"},

  {"german": "die Wassermelone", "english": "watermelon"},
  {"german": "die Pflaume", "english": "plum"},
  {"german": "der Pfirsich", "english": "peach"},
  {"german": "die Himbeere", "english": "raspberry"},
  {"german": "die Blaubeere", "english": "blueberry"},
  {"german": "die Nuss", "english": "nut"},
  {"german": "die Mandel", "english": "almond"},
  {"german": "die Schokolade", "english": "chocolate"},
  {"german": "der Kuchen", "english": "cake"},
  {"german": "der Keks", "english": "cookie"},

  {"german": "das Eis", "english": "ice cream"},
  {"german": "die Süßigkeit", "english": "candy"},
  {"german": "die Torte", "english": "tart / cake"},
  {"german": "der Pudding", "english": "pudding"},
  {"german": "die Chips", "english": "chips"},
  {"german": "die Brezel", "english": "pretzel"},
  {"german": "das Frühstück", "english": "breakfast"},
  {"german": "das Mittagessen", "english": "lunch"},
  {"german": "das Abendessen", "english": "dinner"},
  {"german": "der Snack", "english": "snack"},

  {"german": "das Getränk", "english": "drink"},
  {"german": "das Wasser", "english": "water"},
  {"german": "der Kaffee", "english": "coffee"},
  {"german": "der Tee", "english": "tea"},
  {"german": "der Saft", "english": "juice"},
  {"german": "die Limonade", "english": "lemonade"},
  {"german": "das Bier", "english": "beer"},
  {"german": "der Wein", "english": "wine"},
  {"german": "der Smoothie", "english": "smoothie"},
  {"german": "die Speisekarte", "english": "menu"},

  {"german": "Ich esse gerne Pizza.", "english": "I like to eat pizza."},
  {"german": "Zum Frühstück trinke ich Kaffee.", "english": "I drink coffee for breakfast."},
  {"german": "Wir kaufen frisches Gemüse.", "english": "We buy fresh vegetables."},
  {"german": "Der Apfel ist süß und saftig.", "english": "The apple is sweet and juicy."},
  {"german": "Ich möchte ein Glas Wasser.", "english": "I would like a glass of water."},
  {"german": "Die Suppe ist sehr heiß.", "english": "The soup is very hot."},
  {"german": "Wir kochen heute Abend Pasta.", "english": "We are cooking pasta this evening."},
  {"german": "Ich esse kein Fleisch.", "english": "I do not eat meat."},
  {"german": "Die Banane ist noch nicht reif.", "english": "The banana is not ripe yet."},
  {"german": "Kann ich bitte die Speisekarte haben?", "english": "Can I please have the menu?"},
  {"german": "Das Essen schmeckt sehr gut.", "english": "The food tastes very good."},
  {"german": "Ich nehme einen Salat.", "english": "I’ll take a salad."},
  {"german": "Wir bestellen zwei Getränke.", "english": "We order two drinks."},
  {"german": "Der Kuchen ist lecker.", "english": "The cake is delicious."},
  {"german": "Ich habe Hunger und Durst.", "english": "I am hungry and thirsty."}
]
var Sentences = [
  {"german": "Ich heiße Anna.", "english": "My name is Anna."},
  {"german": "Ich komme aus Polen.", "english": "I come from Poland."},
  {"german": "Ich wohne in Berlin.", "english": "I live in Berlin."},
  {"german": "Ich bin 25 Jahre alt.", "english": "I am 25 years old."},
  {"german": "Ich spreche ein bisschen Deutsch.", "english": "I speak a little German."},

  {"german": "Das ist mein Freund.", "english": "This is my friend."},
  {"german": "Meine Familie ist sehr nett.", "english": "My family is very nice."},
  {"german": "Ich habe zwei Geschwister.", "english": "I have two siblings."},
  {"german": "Wir haben einen Hund.", "english": "We have a dog."},
  {"german": "Sie arbeitet im Büro.", "english": "She works in an office."},

  {"german": "Ich stehe um sieben Uhr auf.", "english": "I get up at seven o’clock."},
  {"german": "Ich frühstücke um acht Uhr.", "english": "I have breakfast at eight."},
  {"german": "Ich gehe zur Arbeit.", "english": "I go to work."},
  {"german": "Ich komme um sechs Uhr nach Hause.", "english": "I come home at six."},
  {"german": "Abends sehe ich fern.", "english": "In the evening I watch TV."},

  {"german": "Ich lerne Deutsch jeden Tag.", "english": "I learn German every day."},
  {"german": "Ich mache meine Hausaufgaben.", "english": "I do my homework."},
  {"german": "Wir lernen zusammen.", "english": "We study together."},
  {"german": "Die Aufgabe ist nicht schwer.", "english": "The task is not difficult."},
  {"german": "Das ist eine gute Idee.", "english": "That is a good idea."},

  {"german": "Ich habe Hunger.", "english": "I am hungry."},
  {"german": "Ich möchte einen Kaffee.", "english": "I would like a coffee."},
  {"german": "Wir bestellen eine Pizza.", "english": "We order a pizza."},
  {"german": "Die Rechnung, bitte.", "english": "The bill, please."},
  {"german": "Das Essen schmeckt gut.", "english": "The food tastes good."},

  {"german": "Wo ist der Bahnhof?", "english": "Where is the train station?"},
  {"german": "Wie viel kostet das?", "english": "How much does that cost?"},
  {"german": "Ich suche ein Hotel.", "english": "I am looking for a hotel."},
  {"german": "Der Bus kommt in fünf Minuten.", "english": "The bus comes in five minutes."},
  {"german": "Wir fahren nach München.", "english": "We are going to Munich."},

  {"german": "Heute ist das Wetter schön.", "english": "The weather is nice today."},
  {"german": "Es regnet den ganzen Tag.", "english": "It rains all day."},
  {"german": "Morgen habe ich keine Zeit.", "english": "Tomorrow I have no time."},
  {"german": "Am Wochenende treffe ich Freunde.", "english": "On the weekend I meet friends."},
  {"german": "Ich habe morgen einen Termin.", "english": "I have an appointment tomorrow."},

  {"german": "Ich kann gut kochen.", "english": "I can cook well."},
  {"german": "Ich muss heute arbeiten.", "english": "I have to work today."},
  {"german": "Ich will ins Kino gehen.", "english": "I want to go to the cinema."},
  {"german": "Darf ich hier sitzen?", "english": "May I sit here?"},
  {"german": "Können Sie mir helfen?", "english": "Can you help me?"},

  {"german": "Ich verstehe das nicht.", "english": "I don’t understand that."},
  {"german": "Können Sie das bitte wiederholen?", "english": "Can you please repeat that?"},
  {"german": "Das ist kein Problem.", "english": "That is not a problem."},
  {"german": "Ich bin müde, aber zufrieden.", "english": "I am tired but satisfied."},
  {"german": "Das Leben ist schön.", "english": "Life is beautiful."},

  {"german": "Ich habe gestern einen Film gesehen.", "english": "I watched a movie yesterday."},
  {"german": "Wir haben am Sonntag Fußball gespielt.", "english": "We played football on Sunday."},
  {"german": "Letzte Woche war ich krank.", "english": "Last week I was sick."},
  {"german": "Ich habe das Buch gelesen.", "english": "I read the book."},
  {"german": "Es war ein guter Tag.", "english": "It was a good day."}
]
var Advanced = [
  {"german": "die Herausforderung", "english": "challenge"},
  {"german": "die Verantwortung", "english": "responsibility"},
  {"german": "die Voraussetzung", "english": "requirement / prerequisite"},
  {"german": "die Entscheidung", "english": "decision"},
  {"german": "die Entwicklung", "english": "development"},
  {"german": "die Fähigkeit", "english": "ability"},
  {"german": "die Möglichkeit", "english": "possibility"},
  {"german": "die Gesellschaft", "english": "society"},
  {"german": "die Forschung", "english": "research"},
  {"german": "die Erfahrung", "english": "experience"},

  {"german": "die Bedeutung", "english": "meaning / significance"},
  {"german": "der Einfluss", "english": "influence"},
  {"german": "die Lösung", "english": "solution"},
  {"german": "die Verbesserung", "english": "improvement"},
  {"german": "der Fortschritt", "english": "progress"},
  {"german": "die Bedingung", "english": "condition"},
  {"german": "die Wirkung", "english": "effect"},
  {"german": "die Erkenntnis", "english": "insight"},
  {"german": "die Zusammenarbeit", "english": "collaboration"},
  {"german": "die Maßnahme", "english": "measure / action"},

  {"german": "nachhaltig", "english": "sustainable"},
  {"german": "effizient", "english": "efficient"},
  {"german": "wesentlich", "english": "essential"},
  {"german": "erheblich", "english": "significant"},
  {"german": "komplex", "english": "complex"},
  {"german": "umfangreich", "english": "extensive"},
  {"german": "verfügbar", "english": "available"},
  {"german": "unabhängig", "english": "independent"},
  {"german": "zuverlässig", "english": "reliable"},
  {"german": "anspruchsvoll", "english": "demanding"},

  {"german": "Obwohl das Projekt komplex ist, haben wir es erfolgreich abgeschlossen.", "english": "Although the project is complex, we completed it successfully."},
  {"german": "Die Entscheidung wurde nach sorgfältiger Analyse getroffen.", "english": "The decision was made after careful analysis."},
  {"german": "Wenn ich mehr Zeit hätte, würde ich ein weiteres Studium beginnen.", "english": "If I had more time, I would start another degree."},
  {"german": "Die Ergebnisse zeigen, dass nachhaltige Maßnahmen notwendig sind.", "english": "The results show that sustainable measures are necessary."},
  {"german": "Je früher wir beginnen, desto schneller erreichen wir unser Ziel.", "english": "The earlier we start, the faster we reach our goal."},

  {"german": "Er behauptet, dass er von dem Problem nichts gewusst habe.", "english": "He claims that he had not known about the problem."},
  {"german": "Trotz der Schwierigkeiten blieb das Team motiviert.", "english": "Despite the difficulties, the team remained motivated."},
  {"german": "Die Studie befasst sich mit den Auswirkungen der Digitalisierung.", "english": "The study deals with the effects of digitalization."},
  {"german": "Es ist wichtig, verschiedene Perspektiven zu berücksichtigen.", "english": "It is important to consider different perspectives."},
  {"german": "Die Zusammenarbeit zwischen den Abteilungen wurde verbessert.", "english": "The collaboration between the departments was improved."},

  {"german": "Während die einen optimistisch sind, bleiben andere skeptisch.", "english": "While some are optimistic, others remain skeptical."},
  {"german": "Die Frage, ob wir expandieren sollten, wird derzeit intensiv diskutiert.", "english": "The question of whether we should expand is currently being discussed intensively."},
  {"german": "Unter diesen Bedingungen ist eine schnelle Lösung kaum möglich.", "english": "Under these conditions, a quick solution is hardly possible."},
  {"german": "Er verfügt über umfangreiche Erfahrung im internationalen Management.", "english": "He has extensive experience in international management."},
  {"german": "Die Maßnahmen zielen darauf ab, die Effizienz zu steigern.", "english": "The measures aim to increase efficiency."},

  {"german": "Angesichts der aktuellen Situation müssen wir flexibel reagieren.", "english": "In view of the current situation, we must respond flexibly."},
  {"german": "Es wurde besclossen, das Budget zu reduzieren.", "english": "It was decided to reduce the budget."},
  {"german": "Die Erkenntnisse könnten langfristig erhebliche Auswirkungen haben.", "english": "The findings could have significant long-term effects."},
  {"german": "Nicht nur die Kosten, sondern auch die Qualität spielt eine entscheidende Rolle.", "english": "Not only the costs, but also the quality plays a decisive role."},
  {"german": "Sollte sich die Lage verschlechtern, werden weitere Maßnahmen ergriffen.", "english": "Should the situation worsen, further measures will be taken."}
]

var Travel = [
  {"german": "die Reise", "english": "trip / journey"},
  {"german": "der Urlaub", "english": "vacation"},
  {"german": "das Hotel", "english": "hotel"},
  {"german": "das Zimmer", "english": "room"},
  {"german": "der Flughafen", "english": "airport"},
  {"german": "das Flugzeug", "english": "airplane"},
  {"german": "der Zug", "english": "train"},
  {"german": "der Bus", "english": "bus"},
  {"german": "das Ticket", "english": "ticket"},
  {"german": "der Koffer", "english": "suitcase"},
  {"german": "der Pass", "english": "passport"},
  {"german": "die Karte", "english": "map"},
  {"german": "die Stadt", "english": "city"},
  {"german": "das Land", "english": "country"},
  {"german": "der Strand", "english": "beach"},
  {"german": "die Berge", "english": "mountains"},
  {"german": "das Meer", "english": "sea"},
  {"german": "das Museum", "english": "museum"},
  {"german": "das Restaurant", "english": "restaurant"},
  {"german": "der Bahnhof", "english": "train station"},
  {"german": "reservieren", "english": "to reserve"},
  {"german": "buchen", "english": "to book"},
  {"german": "reisen", "english": "to travel"},
  {"german": "fliegen", "english": "to fly"},
  {"german": "fahren", "english": "to go / drive"},
  {"german": "ankommen", "english": "to arrive"},
  {"german": "abfahren", "english": "to depart"},
  {"german": "übernachten", "english": "to stay overnight"},
  {"german": "besichtigen", "english": "to visit / sightsee"},
  {"german": "bezahlen", "english": "to pay"},
  {"german": "teuer", "english": "expensive"},
  {"german": "billig", "english": "cheap"},
  {"german": "frei", "english": "free / available"},
  {"german": "besetzt", "english": "occupied"},
  {"german": "nah", "english": "near"},
  {"german": "weit", "english": "far"},
  {"german": "links", "english": "left"},
  {"german": "rechts", "english": "right"},
  {"german": "geradeaus", "english": "straight ahead"},
  {"german": "die Sehenswürdigkeit", "english": "sight / attraction"},
  {"german": "der Tourist", "english": "tourist"},
  {"german": "die Buchung", "english": "booking"},
  {"german": "die Rezeption", "english": "reception"},
  {"german": "der Ausweis", "english": "ID card"},
  {"german": "die Grenze", "english": "border"},
  {"german": "das Gepäck", "english": "luggage"},
  {"german": "die Fahrkarte", "english": "travel ticket"},
  {"german": "der Stadtplan", "english": "city map"},
  {"german": "die Unterkunft", "english": "accommodation"},
  {"german": "die Führung", "english": "guided tour"},

  {"german": "Ich mache Urlaub in Deutschland.", "english": "I am going on vacation in Germany."},
  {"german": "Wir buchen ein Hotelzimmer.", "english": "We are booking a hotel room."},
  {"german": "Das Flugzeug kommt pünktlich an.", "english": "The airplane arrives on time."},
  {"german": "Der Zug fährt um acht Uhr ab.", "english": "The train departs at eight o'clock."},
  {"german": "Wo ist der Bahnhof?", "english": "Where is the train station?"},
  {"german": "Ich brauche ein Ticket nach Berlin.", "english": "I need a ticket to Berlin."},
  {"german": "Der Strand ist sehr schön.", "english": "The beach is very beautiful."},
  {"german": "Wir besuchen ein Museum.", "english": "We are visiting a museum."},
  {"german": "Das Restaurant ist nicht teuer.", "english": "The restaurant is not expensive."},
  {"german": "Können wir hier bezahlen?", "english": "Can we pay here?"},
  {"german": "Das Hotel ist nahe am Zentrum.", "english": "The hotel is near the city center."},
  {"german": "Mein Koffer ist sehr schwer.", "english": "My suitcase is very heavy."},
  {"german": "Ich zeige meinen Pass an der Grenze.", "english": "I show my passport at the border."},
  {"german": "Wir bleiben drei Nächte hier.", "english": "We are staying here for three nights."},
  {"german": "Die Sehenswürdigkeit ist sehr bekannt.", "english": "The attraction is very famous."},
  {"german": "Ist das Zimmer frei?", "english": "Is the room available?"},
  {"german": "Wir fahren mit dem Bus in die Stadt.", "english": "We go to the city by bus."},
  {"german": "Der Tourist fragt nach dem Weg.", "english": "The tourist asks for directions."},
  {"german": "Ich reserviere einen Tisch im Restaurant.", "english": "I reserve a table in the restaurant."},
  {"german": "Die Reise war sehr interessant.", "english": "The trip was very interesting."}
]

var Gaming = [
  {"german": "das Spiel", "english": "game"},
  {"german": "der Spieler", "english": "player"},
  {"german": "das Level", "english": "level"},
  {"german": "die Mission", "english": "mission"},
  {"german": "die Quest", "english": "quest"},
  {"german": "der Gegner", "english": "enemy"},
  {"german": "der Endgegner", "english": "final boss"},
  {"german": "die Fähigkeit", "english": "ability"},
  {"german": "die Erfahrungspunkte", "english": "experience points"},
  {"german": "der Fortschritt", "english": "progress"},

  {"german": "das Inventar", "english": "inventory"},
  {"german": "die Waffe", "english": "weapon"},
  {"german": "die Rüstung", "english": "armor"},
  {"german": "der Schaden", "english": "damage"},
  {"german": "die Heilung", "english": "healing"},
  {"german": "der Spielstand", "english": "save file"},
  {"german": "der Highscore", "english": "high score"},
  {"german": "die Steuerung", "english": "controls"},
  {"german": "die Grafik", "english": "graphics"},
  {"german": "der Soundeffekt", "english": "sound effect"},

  {"german": "die Animation", "english": "animation"},
  {"german": "die Spielmechanik", "english": "game mechanics"},
  {"german": "das Balancing", "english": "balancing"},
  {"german": "die Schwierigkeit", "english": "difficulty"},
  {"german": "der Modus", "english": "mode"},
  {"german": "die Plattform", "english": "platform"},
  {"german": "die Engine", "english": "engine"},
  {"german": "der Code", "english": "code"},
  {"german": "der Fehler", "english": "bug / error"},
  {"german": "das Update", "english": "update"},

  {"german": "der Patch", "english": "patch"},
  {"german": "die Beta-Version", "english": "beta version"},
  {"german": "die Veröffentlichung", "english": "release"},
  {"german": "die Benutzeroberfläche", "english": "user interface"},
  {"german": "die Künstliche Intelligenz", "english": "artificial intelligence"},
  {"german": "die Physik", "english": "physics"},
  {"german": "die Performance", "english": "performance"},
  {"german": "die Ladezeit", "english": "loading time"},
  {"german": "der Server", "english": "server"},
  {"german": "der Multiplayer", "english": "multiplayer"},

  {"german": "der Einzelspieler", "english": "single player"},
  {"german": "das Tutorial", "english": "tutorial"},
  {"german": "die Einstellung", "english": "setting"},
  {"german": "der Charakter", "english": "character"},
  {"german": "die Story", "english": "story"},
  {"german": "die Belohnung", "english": "reward"},
  {"german": "das Ziel", "english": "goal"},
  {"german": "die Entwicklung", "english": "development"},
  {"german": "der Entwickler", "english": "developer"},
  {"german": "das Studio", "english": "studio"},

  {"german": "Das Spiel hat eine spannende Story.", "english": "The game has an exciting story."},
  {"german": "Der Spieler sammelt Erfahrungspunkte.", "english": "The player collects experience points."},
  {"german": "Das Level ist zu schwierig für Anfänger.", "english": "The level is too difficult for beginners."},
  {"german": "Wir arbeiten an einem neuen Update.", "english": "We are working on a new update."},
  {"german": "Die Grafik wurde deutlich verbessert.", "english": "The graphics were significantly improved."},

  {"german": "Die Steuerung fühlt sich sehr flüssig an.", "english": "The controls feel very smooth."},
  {"german": "Der Entwickler behebt gerade einen Fehler.", "english": "The developer is currently fixing a bug."},
  {"german": "Das Balancing muss noch angepasst werden.", "english": "The balancing still needs to be adjusted."},
  {"german": "Die Beta-Version wird nächste Woche veröffentlicht.", "english": "The beta version will be released next week."},
  {"german": "Viele Spieler spielen im Multiplayer-Modus.", "english": "Many players play in multiplayer mode."},

  {"german": "Der Server ist momentan nicht erreichbar.", "english": "The server is currently not reachable."},
  {"german": "Das Tutorial erklärt die wichtigsten Funktionen.", "english": "The tutorial explains the most important functions."},
  {"german": "Die Ladezeit ist noch etwas zu lang.", "english": "The loading time is still a bit too long."},
  {"german": "Die Künstliche Intelligenz reagiert sehr realistisch.", "english": "The artificial intelligence reacts very realistically."},
  {"german": "Wir testen das Spiel auf verschiedenen Plattformen.", "english": "We are testing the game on different platforms."},

  {"german": "Das Studio plant eine große Veröffentlichung.", "english": "The studio is planning a big release."},
  {"german": "Der Charakter kann neue Fähigkeiten freischalten.", "english": "The character can unlock new abilities."},
  {"german": "Die Spieler erhalten eine Belohnung nach der Mission.", "english": "The players receive a reward after the mission."},
  {"german": "Die Entwicklung des Spiels dauert länger als geplant.", "english": "The development of the game takes longer than planned."},
  {"german": "Das Ziel ist es, ein einzigartiges Spielerlebnis zu schaffen.", "english": "The goal is to create a unique gaming experience."}
]

var All = [
  {
	"name": "Basic German",
	"description": "100 everyday German words for beginners. Covers everyday expressions, common verbs, useful nouns, adjectives, question words, and numbers. Perfect for A1 level learners and first-time users.",
	"array": Standard
  },
  {
	"name": "Animals",
	"description": "Learn German through the world of animals. Fun and easy sentences help you remember words while talking about pets, wild animals, and farm life.",
	"array": Animals
  },
  {
	"name": "Food",
	"description": "Explore German through food! Practice useful words and sentences for shopping, cooking, and ordering your favorite meals.",
	"array": Food
  },

  {
	"name": "Travel",
	"description": "Get ready for your next trip! Learn words and sentences to help with transport, hotels, sightseeing, and navigating new places.",
	"array": Travel
  },

  {
	"name": "Daily Sentences",
	"description": "Everyday sentences for real-life situations. Perfect for greetings, daily routines, travel, and chatting with friends.",
	"array": Sentences
  },
  {
	"name": "Advanced German",
	"description": "Take your German to the next level. Learn useful words and sentences for professional topics, abstract ideas, and complex conversations.",
	"array": Advanced
  },
{
	"name": "Gaming & Game Dev",
	"description": "Dive into German through games! Learn words and sentences about gameplay, mechanics, and game development while having fun.",
	"array": Gaming
  },
  
]
